FROM linuxserver/blender:4.2.3
USER root
RUN apt-get update && apt-get install -y python3-pip ffmpeg && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . .
RUN pip3 install --break-system-packages celery redis sqlalchemy asyncpg
ENTRYPOINT ["celery","-A","app.workers.celery_app:celery_app","worker","-Q","blender","--loglevel=INFO"]
